### ISSUE TITLE
Request feature: orange-tangerine classifier

### ISSUE THREAD

**Issue by pntt3011** [egliette/Lemon_Lime_classifier#1]
Do you have any pretrained model for orange-tangerine classifier @egliette? I need it for my school project. Thank you very much.

**Comment by egliette** [comment]
To my dear friend,
Thank you for your interest in my project, I have tried to classify
tangerines and oranges before but got stuck on the crawl step (I tried
using Bing Image but the dataset is too garbage). If you have the above
data set, please send it to me, I will do the rest for you.
Best regards,
Le Minh Tu

Vào Th 6, 28 thg 1, 2022 vào lúc 12:51 shigure3011 <
***@***.***> đã viết:

**Comment by pntt3011** [comment]
Thank you for your reply!
I've found a dataset about it on [kaggle](https://www.kaggle.com/mohamedmabdelhamid/knn-orange-and-tangerine). Too bad it just uses their features instead of the images. I will try collect some data by hand and give it to you later.

**Comment by egliette** [comment]
Hello,
I appreciate you helping me find the dataset, but my aim is to create a
website for sorting fruit through images (which I have implemented on the
following site:
https://mybinder.org/v2/gh/egliette/Lemon_Orange_classifier/HEAD?urlpath=%2Fvoila%2Frender%2FLemon_Orange_Classifier.ipynb)
for the sake of simplicity of input (it would be boring to enter a bunch of
features just to classify two fruits). Thank you again for your enthusiasm.
Sincerely,
Lê Minh Tú

Vào Th 6, 28 thg 1, 2022 vào lúc 21:01 shigure3011 <
***@***.***> đã viết:
